Oleksii_W9_Q1
IvanRemez/Smart_Cookies pull request #35
Opened 2023-03-16 15:10 UTC by madadm

Q1

2023-03-16 17:01 UTC, IvanRemez requested changes
You deleted Sopio's test print statements in the Main without adding your own tests. Please fix prior to merge.

2023-03-19 20:58 UTC, ihccik requested changes

2023-03-19 20:58 UTC, ihccik commented on src/main/java/Solutions/week09/Q1_LengthOfLastWord.java
> -        System.out.println(LengthOfLastWord_Sopo(str3_Sopo));
Why those lines are deleted. It belongs to another Cookie :)

2023-03-19 20:58 UTC, ihccik commented on src/main/java/Solutions/week09/Q1_LengthOfLastWord.java
> +    public static int Oleksii_LenghtOfTheLastWord(String word){
Can you please call your method from main method

2023-05-18 15:19 UTC, closed without merging