added solution
IvanRemez/Smart_Cookies pull request #9
Opened 2023-02-22 18:09 UTC by ZehraSarigedikDemircioglu

Can you please pull my solution to master branch?

2023-02-22 19:10 UTC, IvanRemez requested changes

2023-02-22 19:10 UTC, IvanRemez commented on src/main/java/Solutions/week6/ValidAnagram.java
> +public class ValidAnagram {
Please add your solutions to the existing Q1_ValidAnagram without creating a new class.

2023-02-22 19:10 UTC, IvanRemez commented on src/main/java/Solutions/week6/ValidAnagramStream.java
> +public class ValidAnagramStream {
Please add your solutions to the existing Q1_ValidAnagram without creating a new class. Just move your method to that class without deleting anything else. Also the calls from Main method can be transferred over.

2023-02-23 15:29 UTC, ZehraSarigedikDemircioglu commented
I added my solutions to the existed Q1_ValidAnagram and Q2_ValidPalindrome.

2023-02-23 17:48 UTC, IvanRemez approved these changes
Much better! Good job!

2023-02-23 17:48 UTC, merged